apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "test2"
  description: "test2"
  tags:
    - sx
    - template
  links:
    - url: 'https://grafana.apps.cluster1.mcp.pitagora.at/d/KRlE7mE4z/4-golden-signals-sx-cnp?orgId=1&refresh=5s&var-namespace=suxess-it-qa&var-workload=test2&var-service=test2'
      title: Grafana SRE Metrics
      icon: web
    - url: http://test2-suxess-it-qa.apps.cluster1.mcp.pitagora.at
      title: test2 Service Route
      icon: web
  annotations:
    github.com/project-slug: phac008/test2-gitops
    backstage.io/kubernetes-id: test2
    kubecost.com/deployment-name: test2
    argocd/app-name: test2-qa
    backstage.io/kubernetes-namespace: suxess-it-qa
    backstage.io/techdocs-ref: dir:.
    grafana/dashboard-selector: "(tags @> '4GoldenSignals')"
    grafana/overview-dashboard: 'https://grafana.apps.cluster1.mcp.pitagora.at/d/KRlE7mE4z/4-golden-signals-sx-cnp?orgId=1&refresh=5s&var-namespace=suxess-it-qa&var-workload=test2&var-service=test2'
spec:
  type: service
  lifecycle: experimental
  owner: user:default/philipp.achmueller
  system: system:test2
  dependsOn:
    - resource:argocd
