apiVersion: apps/v1
kind: Deployment
metadata:
  name: test2
  namespace: suxess-it-qa
  labels:
    app: test2
    backstage.io/kubernetes-id: test2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: test2
  template:
    metadata:
      labels:
        app: test2
        backstage.io/kubernetes-id: test2
    spec:
      containers:
#      - image: quay.io/rbaumgar/monitor-demo-app-jvm
      - image: quay.io/rbaumgar/monitor-demo-app-jvm
        imagePullPolicy: Always
        name: test2