apiVersion: v1
kind: Service
metadata:
  name: test2
  namespace: suxess-it-qa
  labels:
    app: test2
    backstage.io/kubernetes-id: test2
spec:
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: test2
  type: ClusterIP